### ISSUE TITLE
Teradata JDBC Driver 16.20.00.13 is missing tdgssconfig.jar

### ISSUE THREAD

**Issue by LennartAtExasol** [exasol/teradata-virtual-schema#3]
The latest version of Teradatas JDBC driver is no longer provided with the tdgssconfig.jar file. However the tdgssconfig.jar from release 15.10.00.37 seems to be compatible with terajdbc4.jar from 16.20.00.13. This should be addressed in the documentation or tdgssconfig.jar should no longer be necessary.

**Comment by AnastasiiaSergienko** [comment]
The available for downloading driver version I found on the official website (https://downloads.teradata.com/download/connectivity/jdbc-driver):

* 15.00.00.35 -> has tdgssconfig.jar
* 16.10.00.07 -> has tdgssconfig.jar

* 16.20.00.13 -> doesn't have tdgssconfig.jar
* 17.00.00.03 -> doesn't have tdgssconfig.jar

**Comment by AnastasiiaSergienko** [comment]
The documentation also mentions the following: Beginning with Teradata JDBC Driver 16.20.00.11, tdgssconfig.jar is no longer part
of the Teradata JDBC Driver, and your classpath should not include tdgssconfig.jar.

I've also tested the Virtual Schema with 17.00.00.03 driver but without  tdgssconfig.jar. It works correctly. So we will document this information about drivers.
